# Generated by Django 4.2.5 on 2023-09-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='age',
            new_name='code',
        ),
        migrations.AddField(
            model_name='customuser',
            name='loc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tel',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
