# Generated by Django 4.2.5 on 2023-09-18 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usac', '0004_rename_code_customuser_food_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='food_code',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
