# Generated by Django 4.2.5 on 2023-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usac', '0005_alter_customuser_food_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='food_code',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='loc',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
