# Generated by Django 4.2.5 on 2023-09-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyeruser',
            name='age',
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='food_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='loc',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='buyeruser',
            name='tel',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
