# Generated by Django 4.2.5 on 2023-09-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_remove_buyeruser_age_buyeruser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeruser',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
